post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJleGRhdmluY2kxIiwiaWQiOiI1ZGE5YzRkN2NiMzg5ZTA4MDQzNTI3ZjAiLCJpYXQiOjE1NzIyNDM3MjV9.ETj4ipMBU3JIUaH3YbPPjjpjtxPrRSmEgDD7tQMq9_c

{
  "author": "Rex Davinci",
  "title": "Python is great",
  "url": "abdhafizahmed.com"
}
