post http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJleGRhdmluY2kiLCJpZCI6IjVkYTliNzFmNGU2YTMzM2NjNDlkOWE0OSIsImlhdCI6MTU3MTQxMjIwOX0.Yd5CLoN-L6-n7qVaZHZFFEovJULPVf52PcrYXNIQp9A

{
  "author": "Rex",
  "title": "Javascript is coming I",
  "url": "www.google.com"
}
